# Generated by Django 4.1 on 2022-10-12 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('users', '0001_initial'), ('users', '0002_bookmode'), ('users', '0003_delete_bookmode'), ('users', '0004_profilemodel_friends'), ('users', '0005_friend_request'), ('users', '0006_filters_gallery_icon_pricing_service_testimonial_and_more'), ('users', '0007_rename_filters_filter'), ('users', '0008_remove_profile_icons_remove_profile_navbar_and_more'), ('users', '0009_remove_profile_services_service_user'), ('users', '0010_remove_profile_gallery_remove_profile_pricing_and_more'), ('users', '0011_remove_profilemodel_profile_link_delete_linkmodel'), ('users', '0012_service_details_alter_gallery_filter_and_more'), ('users', '0013_alter_service_details'), ('users', '0014_alter_gallery_user'), ('users', '0015_alter_gallery_filter'), ('users', '0016_profile_year'), ('users', '0017_alter_profile_avatar_alter_profile_favicon_and_more'), ('users', '0018_alter_gallery_photo'), ('users', '0019_profile_facebook_profile_github_profile_google_plus_and_more'), ('users', '0020_profile_instagram'), ('users', '0021_socials'), ('users', '0022_rename_socials_social'), ('users', '0023_remove_profile_facebook_remove_profile_github_and_more'), ('users', '0024_pricing_title_alter_pricing_item_amount_and_more'), ('users', '0025_pricing_featured'), ('users', '0026_alter_pricing_price'), ('users', '0027_pricing_features'), ('users', '0028_navbar'), ('users', '0029_navbar_details'), ('users', '0030_profile_gallerys_profile_gallerys_details_and_more'), ('users', '0031_profile_if_gallerys_profile_if_pricings_and_more'), ('users', '0032_profile_if_ourteam_profile_ourteam_and_more'), ('users', '0033_profile_contact_profile_contact_details_and_more'), ('users', '0034_alter_profile_gallerys_alter_profile_ourteam_and_more'), ('users', '0035_profile_if_who_we_are_profile_who_we_are_and_more'), ('users', '0036_navbar_category_navbar_photo'), ('users', '0037_alter_navbar_category'), ('users', '0038_alter_navbar_category'), ('users', '0039_remove_navbar_category'), ('users', '0040_navbar_category'), ('users', '0041_alter_navbar_category'), ('users', '0042_remove_profile_birthday_remove_profile_contact_and_more'), ('users', '0043_navbar_background_color_navbar_background_photo'), ('users', '0044_alter_navbar_category_alter_service_user'), ('users', '0045_service_name'), ('users', '0046_rename_name_service_nav_remove_service_user'), ('users', '0047_service_navbar'), ('users', '0048_remove_gallery_user_remove_pricing_user_gallery_nav_and_more'), ('users', '0049_counters'), ('users', '0050_rename_counters_counter'), ('users', '0051_counter_photo_counter_title_alter_navbar_category'), ('users', '0052_remove_counter_photo_remove_counter_title_and_more'), ('users', '0053_profile_button_profile_destination')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=30)),
                ('icons', models.CharField(max_length=30)),
                ('fav', models.CharField(max_length=30)),
                ('shortcut', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('motto', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('button', models.CharField(blank=True, max_length=30, null=True)),
                ('destination', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
                ('icon', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('details', models.CharField(blank=True, max_length=300, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('category', models.TextField(blank=True, choices=[('pricing', 'Pricing'), ('services', 'services'), ('services2', 'services2'), ('portfolio', 'gallery'), ('portfolio2', 'gallery2'), ('about', 'about'), ('team', 'team'), ('testimonial', 'testimonial'), ('contact', 'contact'), ('counter', 'counter')], null=True)),
                ('background_color', models.BooleanField(default=False)),
                ('background_photo', models.ImageField(blank=True, null=True, upload_to='photo/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(blank=True, max_length=30, null=True)),
                ('icon', models.CharField(blank=True, max_length=30, null=True)),
                ('details', models.CharField(blank=True, max_length=300, null=True)),
                ('nav', models.CharField(blank=True, max_length=30, null=True)),
                ('navbar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.navbar')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.filter')),
                ('nav', models.CharField(blank=True, max_length=30, null=True)),
                ('navbar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.navbar')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('saving', models.CharField(blank=True, max_length=20, null=True)),
                ('payment', models.CharField(blank=True, max_length=20, null=True)),
                ('item_amount', models.IntegerField(blank=True, null=True)),
                ('item_quantity', models.CharField(blank=True, max_length=10, null=True)),
                ('item_name', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('featured', models.BooleanField(default=True)),
                ('features', models.BooleanField(default=False)),
                ('nav', models.CharField(blank=True, max_length=30, null=True)),
                ('navbar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.navbar')),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('navbar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.navbar')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=30)),
                ('quote', models.CharField(max_length=100)),
                ('nav', models.CharField(blank=True, max_length=30, null=True)),
                ('navbar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.navbar')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
