# Generated by Django 4.0.1 on 2022-11-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.IntegerField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
