# Generated by Django 4.1 on 2022-08-29 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bookmode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bookmode',
        ),
    ]
