# Generated by Django 4.0.1 on 2022-11-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_about_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='order',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
