# Generated by Django 4.1 on 2022-09-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_filters_gallery_icon_pricing_service_testimonial_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filters',
            new_name='Filter',
        ),
    ]
