# Generated by Django 4.1 on 2022-09-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_filters_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='icons',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='navbar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stylesheet',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zite',
        ),
        migrations.AddField(
            model_name='profile',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='customers/profiles/logo/'),
        ),
    ]
