# Generated by Django 4.0.1 on 2022-11-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_title_about_background_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navbar',
            old_name='background_photo',
            new_name='background_image',
        ),
        migrations.RemoveField(
            model_name='navbar',
            name='background_color',
        ),
        migrations.AddField(
            model_name='navbar',
            name='background',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
