# Generated by Django 4.0.1 on 2022-11-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_background_photo_navbar_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='category',
            field=models.TextField(blank=True, choices=[('pricing', 'Pricing'), ('services', 'services'), ('services2', 'services2'), ('portfolio', 'gallery'), ('portfolio2', 'gallery2'), ('About', 'About'), ('team', 'team'), ('testimonial', 'testimonial'), ('contact', 'contact'), ('counter', 'counter')], null=True),
        ),
    ]
