# Generated by Django 4.0.1 on 2022-11-02 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('styling', '0009_alter_image_navbar_id_alter_imageanimation_navbar'),
        ('users', '0010_alter_navbar_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='filter',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='navbar',
        ),
        migrations.RemoveField(
            model_name='navbar',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='navbar',
        ),
        migrations.RemoveField(
            model_name='service',
            name='navbar',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='navbar',
        ),
        migrations.DeleteModel(
            name='Counter',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='Navbar',
        ),
        migrations.DeleteModel(
            name='Pricing',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
