# Generated by Django 4.0.1 on 2022-11-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_about_remove_gallery_filter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_info',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
