# Generated by Django 4.1 on 2022-09-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_service_details_alter_gallery_filter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='details',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
