# Generated by Django 4.1 on 2022-09-30 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_gallery_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.filter'),
        ),
    ]
