# Generated by Django 4.1 on 2022-10-05 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_socials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Socials',
            new_name='Social',
        ),
    ]
