# Generated by Django 4.1 on 2022-10-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_pricing_title_alter_pricing_item_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='featured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
