# Generated by Django 4.1 on 2022-10-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_pricing_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
