# Generated by Django 4.1 on 2022-10-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_pricing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='features',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
