# Generated by Django 4.1 on 2022-10-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_profile_gallerys_profile_gallerys_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='if_gallerys',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='if_pricings',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='if_services',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='if_testimonial',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
