# Generated by Django 4.1 on 2022-10-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_profile_if_ourteam_profile_ourteam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_details',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='if_contact',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
