# Generated by Django 4.1 on 2022-10-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_profile_contact_profile_contact_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gallerys',
            field=models.CharField(blank=True, default='Gallery', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ourteam',
            field=models.CharField(blank=True, default='Our Team', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pricings',
            field=models.CharField(blank=True, default='Pricing', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='services',
            field=models.CharField(blank=True, default='Services', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='testimonial',
            field=models.CharField(blank=True, default='Testimonial', max_length=30, null=True),
        ),
    ]
