# Generated by Django 4.1 on 2022-10-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_profile_gallerys_alter_profile_ourteam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='if_who_we_are',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='who_we_are',
            field=models.CharField(blank=True, default='Who Are We', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='who_we_are_details',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
