# Generated by Django 4.1 on 2022-10-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_profile_if_who_we_are_profile_who_we_are_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='category',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('pricing', 'pricing'), ('services', 'services'), ('gallery', 'gallery'), ('about', 'about')], null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
