# Generated by Django 4.1 on 2022-10-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_navbar_category_navbar_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='category',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('pricing', 'pricing'), ('services', 'services'), ('gallery', 'gallery'), ('about', 'about'), ('team', 'team'), ('contact', 'contact')], null=True),
        ),
    ]
