# Generated by Django 4.1 on 2022-10-09 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_navbar_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbar',
            name='category',
        ),
    ]
