# Generated by Django 4.1 on 2022-10-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_navbar_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='category',
            field=models.TextField(blank=True, choices=[('pricing', 'Pricing'), ('services', 'services'), ('gallery', 'gallery'), ('about', 'about'), ('team', 'team'), ('contact', 'contact')], null=True),
        ),
    ]
