# Generated by Django 4.1 on 2022-10-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_service_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='nav',
        ),
        migrations.RemoveField(
            model_name='service',
            name='user',
        ),
    ]
