# Generated by Django 4.1 on 2022-10-10 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_rename_name_service_nav_remove_service_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='navbar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.navbar'),
        ),
    ]
