# Generated by Django 4.1 on 2022-10-10 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_service_navbar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='user',
        ),
        migrations.AddField(
            model_name='gallery',
            name='nav',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='navbar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.navbar'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='nav',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='navbar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.navbar'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='nav',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='navbar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.navbar'),
        ),
    ]
