# Generated by Django 4.1 on 2022-10-10 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_counters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Counters',
            new_name='Counter',
        ),
    ]
