# Generated by Django 4.1 on 2022-10-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_counter_photo_counter_title_alter_navbar_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='title',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
