# Generated by Django 4.1 on 2022-10-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_remove_counter_photo_remove_counter_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='button',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='destination',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
