# Generated by Django 4.1 on 2022-10-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0053_profile_button_profile_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='background_color',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='featured',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='features',
            field=models.BooleanField(),
        ),
    ]
