# Generated by Django 4.1 on 2022-10-20 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_alter_navbar_background_color_alter_pricing_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('features', models.BooleanField()),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('featured', models.BooleanField()),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('saving', models.CharField(blank=True, max_length=20, null=True)),
                ('payment', models.CharField(blank=True, max_length=20, null=True)),
                ('item_amount', models.IntegerField(blank=True, null=True)),
                ('item_quantity', models.CharField(blank=True, max_length=10, null=True)),
                ('item_name', models.CharField(blank=True, max_length=30, null=True)),
                ('amount', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=30, null=True)),
                ('message', models.CharField(blank=True, max_length=30, null=True)),
                ('navbar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.navbar')),
            ],
        ),
    ]
