# Generated by Django 4.1 on 2022-10-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='order',
            name='features',
        ),
        migrations.RemoveField(
            model_name='order',
            name='nav',
        ),
        migrations.RemoveField(
            model_name='order',
            name='navbar',
        ),
    ]
