# Generated by Django 4.1 on 2022-10-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_remove_order_featured_remove_order_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
