# Generated by Django 4.0.1 on 2022-11-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_style', models.CharField(max_length=200)),
                ('image_animation', models.CharField(blank=True, max_length=200, null=True)),
                ('border_radius', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageAnimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animation', models.TextField(blank=True, choices=[('overlay', 'overlay'), ('middle', 'middle'), ('polaroid', 'polaroid'), ('slide right', 'slide right'), ('slide left', 'slide left'), ('slide up', 'slide up'), ('slide down', 'slide down')], null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animation', models.TextField(blank=True, choices=[('blur', 'blur'), ('brightness', 'brightness'), ('contrast', 'contrast'), ('grayscale', 'grayscale'), ('invert', 'invert'), ('opacity', 'opacity'), ('saturate', 'saturate'), ('sepia', 'sepia'), ('hue-rotate', 'hue-rotate'), ('drop-shadow', 'drop-shadow')], null=True)),
                ('value', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
