# Generated by Django 4.0.1 on 2022-11-02 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_background_photo_navbar_background_image_and_more'),
        ('styling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanimation',
            name='navbar',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='users.navbar'),
            preserve_default=False,
        ),
    ]
