# Generated by Django 4.0.1 on 2022-11-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('styling', '0002_imageanimation_navbar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageanimation',
            name='navbar',
        ),
    ]
