# Generated by Django 4.0.1 on 2022-11-02 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_navbar_category'),
        ('styling', '0005_alter_imageanimation_navbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageanimation',
            name='navbar',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='nav_ref', to='users.navbar'),
        ),
    ]
