# Generated by Django 4.0.1 on 2022-11-02 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_navbar_category'),
        ('styling', '0006_alter_imageanimation_navbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='navbar_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='users.navbar'),
            preserve_default=False,
        ),
    ]
