# Generated by Django 4.0.1 on 2022-11-02 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_navbar_category'),
        ('styling', '0007_image_navbar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageanimation',
            name='navbar',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='nav_ref', to='users.navbar'),
        ),
    ]
