# Generated by Django 4.0.1 on 2022-11-02 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firsts', '0001_initial'),
        ('styling', '0008_alter_imageanimation_navbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='navbar_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firsts.navbar'),
        ),
        migrations.AlterField(
            model_name='imageanimation',
            name='navbar',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='nav_ref', to='firsts.navbar'),
        ),
    ]
