# Generated by Django 4.0.1 on 2022-11-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styling', '0009_alter_image_navbar_id_alter_imageanimation_navbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_color', models.CharField(blank=True, max_length=20, null=True)),
                ('footer_direction', models.CharField(blank=True, max_length=20, null=True)),
                ('footer_style', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_color', models.CharField(blank=True, max_length=20, null=True)),
                ('header_color_hover', models.CharField(blank=True, max_length=20, null=True)),
                ('header_style', models.CharField(blank=True, max_length=20, null=True)),
                ('header_animation', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_color', models.CharField(blank=True, max_length=20, null=True)),
                ('nav_direction', models.CharField(blank=True, max_length=20, null=True)),
                ('nav_style', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
