# Generated by Django 4.0.1 on 2022-11-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styling', '0010_footer_header_nav'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='footer_color',
            new_name='bg_color',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='footer_direction',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='footer_style',
            new_name='direction',
        ),
        migrations.AddField(
            model_name='footer',
            name='link_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link_hover_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='style',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
