# Generated by Django 4.0.1 on 2022-11-05 07:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('styling', '0013_rename_header_color_hover_header_header_hover_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
