# Generated by Django 4.0.1 on 2022-11-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styling', '0015_footer_user_header_user_image_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='direction',
            field=models.TextField(choices=[('top', 'top'), ('bottom', 'bottom')], default='top'),
            preserve_default=False,
        ),
    ]
