# Generated by Django 4.0.1 on 2022-11-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styling', '0016_alter_nav_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='motto_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='motto_hover_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='title_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='title_hover_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nav',
            name='direction',
            field=models.TextField(choices=[('top', 'top'), ('fixed-top', 'fixed-top'), ('fixed-bottom', 'fixed-bottom')]),
        ),
    ]
