# Generated by Django 4.0.1 on 2022-11-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styling', '0017_header_motto_color_header_motto_hover_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='motto_size',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='title_size',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
