# Generated by Django 4.0.1 on 2022-11-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styling', '0018_header_motto_size_header_title_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='header_stroke',
            field=models.IntegerField(blank=True, default=70, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='heaer_stroke_color',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='motto_animation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='motto_stroke',
            field=models.IntegerField(blank=True, default=70, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='motto_stroke_color',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='motto_style',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='text_animation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='text_stroke',
            field=models.IntegerField(blank=True, default=70, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='text_stroke_color',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='text_style',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='title_animation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='title_stroke',
            field=models.IntegerField(blank=True, default=70, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='title_stroke_color',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='title_style',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='title_color',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='title_size',
            field=models.IntegerField(blank=True, default=70, null=True),
        ),
    ]
