# Generated by Django 4.0.1 on 2022-11-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_order_amount_alter_order_contact_info_and_more'),
        ('firsts', '0003_alter_navbar_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbar',
            name='user',
        ),
        migrations.AddField(
            model_name='navbar',
            name='user',
            field=models.ManyToManyField(blank=True, to='users.Profile'),
        ),
    ]
