# Generated by Django 4.0.1 on 2022-11-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firsts', '0004_remove_navbar_user_navbar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='category',
            field=models.TextField(blank=True, choices=[('pricing', 'pricing'), ('services', 'services'), ('portfolio', 'gallery'), ('about', 'about'), ('team', 'team'), ('testimonial', 'testimonial'), ('contact', 'contact'), ('counter', 'counter')], null=True),
        ),
    ]
