# Generated by Django 4.0.1 on 2022-11-03 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='nav',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='nav',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='nav',
        ),
        migrations.RemoveField(
            model_name='service',
            name='nav',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='nav',
        ),
    ]
