# Generated by Django 4.0.1 on 2022-11-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbars', '0002_remove_counter_nav_remove_gallery_nav_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='payment',
        ),
        migrations.AddField(
            model_name='pricing',
            name='payment_style',
            field=models.TextField(choices=[('cash', 'cash/card'), ('oo', 'one off'), ('w', 'weekly'), ('o3m', 'over 3 months'), ('o6m', 'over 6 months'), ('ay', 'over a year')], default=1),
            preserve_default=False,
        ),
    ]
